package com.company.scopery.modules.iam.shared.constant;

public final class IamPermissionCodes {

    private IamPermissionCodes() {}

    public static final String SYSTEM_IAM_MANAGEMENT = "SYSTEM_IAM_MANAGEMENT";
    public static final String SYSTEM_RESOURCE_MANAGEMENT = "SYSTEM_RESOURCE_MANAGEMENT";
    public static final String SYSTEM_GOVERNANCE_MANAGEMENT = "SYSTEM_GOVERNANCE_MANAGEMENT";
    public static final String SYSTEM_NOTIFICATION_MANAGEMENT = "SYSTEM_NOTIFICATION_MANAGEMENT";
    public static final String SYSTEM_EVENT_REGISTRY_MANAGEMENT = "SYSTEM_EVENT_REGISTRY_MANAGEMENT";
    public static final String ORGANIZATION_MANAGEMENT = "ORGANIZATION_MANAGEMENT";
    public static final String WORKSPACE_MANAGEMENT = "WORKSPACE_MANAGEMENT";
    public static final String WORKSPACE_ACCESS_MANAGEMENT = "WORKSPACE_ACCESS_MANAGEMENT";
    public static final String WORKSPACE_ROLE_MANAGEMENT = "WORKSPACE_ROLE_MANAGEMENT";
    public static final String TEAM_MANAGEMENT = "TEAM_MANAGEMENT";
    public static final String WORKSPACE_MEMBER_MANAGEMENT = "WORKSPACE_MEMBER_MANAGEMENT";
    public static final String TEAM_MEMBER_MANAGEMENT = "TEAM_MEMBER_MANAGEMENT";
    public static final String IAM_USER_MANAGEMENT = "IAM_USER_MANAGEMENT";
    public static final String IAM_ROLE_MANAGEMENT = "IAM_ROLE_MANAGEMENT";
    public static final String IAM_RIGHT_MANAGEMENT = "IAM_RIGHT_MANAGEMENT";
    public static final String ACCESS_GRANT_MANAGEMENT = "ACCESS_GRANT_MANAGEMENT";
    public static final String ROLE_MANAGEMENT = "ROLE_MANAGEMENT";
    public static final String DOCUMENT_TYPE_MANAGEMENT = "DOCUMENT_TYPE_MANAGEMENT";
    public static final String DOCUMENT_TYPE_FIELD_MANAGEMENT = "DOCUMENT_TYPE_FIELD_MANAGEMENT";
    public static final String KNOWLEDGE_CLASSIFICATION_MANAGEMENT = "KNOWLEDGE_CLASSIFICATION_MANAGEMENT";
    public static final String DOCUMENT_MANAGEMENT = "DOCUMENT_MANAGEMENT";
    public static final String GOVERNANCE_MANAGEMENT = "GOVERNANCE_MANAGEMENT";
    public static final String NOTIFICATION_MANAGEMENT = "NOTIFICATION_MANAGEMENT";

    public static final String PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT";
    public static final String PROJECT_PHASE_MANAGEMENT = "PROJECT_PHASE_MANAGEMENT";
    public static final String PROJECT_WBS_MANAGEMENT = "PROJECT_WBS_MANAGEMENT";
    public static final String PROJECT_TASK_MANAGEMENT = "PROJECT_TASK_MANAGEMENT";
    public static final String PHASE_DEFINITION_MANAGEMENT = "PHASE_DEFINITION_MANAGEMENT";
    public static final String PROJECT_TEMPLATE_MANAGEMENT = "PROJECT_TEMPLATE_MANAGEMENT";

    public static final String CAPACITY_CALENDAR_MANAGEMENT = "CAPACITY_CALENDAR_MANAGEMENT";
    public static final String CAPACITY_PROFILE_MANAGEMENT = "CAPACITY_PROFILE_MANAGEMENT";
    public static final String PROJECT_ALLOCATION_MANAGEMENT = "PROJECT_ALLOCATION_MANAGEMENT";
    public static final String CAPACITY_MANAGEMENT = "CAPACITY_MANAGEMENT";

    public static final String COST_ROLE_MANAGEMENT = "COST_ROLE_MANAGEMENT";
    public static final String RATE_CARD_MANAGEMENT = "RATE_CARD_MANAGEMENT";
    public static final String RATE_CARD_LINE_MANAGEMENT = "RATE_CARD_LINE_MANAGEMENT";
    public static final String ESTIMATION_MANAGEMENT = "ESTIMATION_MANAGEMENT";
    public static final String PROJECT_FINANCE_MANAGEMENT = "PROJECT_FINANCE_MANAGEMENT";
    public static final String QUOTE_MANAGEMENT = "QUOTE_MANAGEMENT";
    public static final String PROJECT_BASELINE_MANAGEMENT = "PROJECT_BASELINE_MANAGEMENT";
    public static final String CHANGE_REQUEST_MANAGEMENT = "CHANGE_REQUEST_MANAGEMENT";
    public static final String CHANGE_ORDER_MANAGEMENT = "CHANGE_ORDER_MANAGEMENT";
    public static final String PROJECT_NOTIFICATION_MANAGEMENT = "PROJECT_NOTIFICATION_MANAGEMENT";
    public static final String AI_PROJECT_PLANNING_MANAGEMENT = "AI_PROJECT_PLANNING_MANAGEMENT";
    public static final String REPORTING_MANAGEMENT = "REPORTING_MANAGEMENT";
    public static final String SCOPE_MANAGEMENT = "SCOPE_MANAGEMENT";
    public static final String DELIVERABLE_MANAGEMENT = "DELIVERABLE_MANAGEMENT";
    public static final String RAID_MANAGEMENT = "RAID_MANAGEMENT";
    public static final String DECISION_MANAGEMENT = "DECISION_MANAGEMENT";
    public static final String QUALITY_MANAGEMENT = "QUALITY_MANAGEMENT";
    public static final String TEST_MANAGEMENT = "TEST_MANAGEMENT";
    public static final String DEFECT_MANAGEMENT = "DEFECT_MANAGEMENT";
    public static final String RELEASE_MANAGEMENT = "RELEASE_MANAGEMENT";
    public static final String DEPLOYMENT_MANAGEMENT = "DEPLOYMENT_MANAGEMENT";
    public static final String DOCUMENT_HUB_MANAGEMENT = "DOCUMENT_HUB_MANAGEMENT";
    public static final String REQUIREMENT_MANAGEMENT = "REQUIREMENT_MANAGEMENT";
    public static final String EXTERNAL_PARTY_MANAGEMENT = "EXTERNAL_PARTY_MANAGEMENT";
    public static final String CLIENT_PORTAL_MANAGEMENT = "CLIENT_PORTAL_MANAGEMENT";
    public static final String COLLABORATION_MANAGEMENT = "COLLABORATION_MANAGEMENT";
    public static final String COMMENT_MANAGEMENT = "COMMENT_MANAGEMENT";
    public static final String PRODUCTIVITY_MANAGEMENT = "PRODUCTIVITY_MANAGEMENT";
    public static final String CONFIGURATION_MANAGEMENT = "CONFIGURATION_MANAGEMENT";
    public static final String OBJECT_GOVERNANCE_MANAGEMENT = "OBJECT_GOVERNANCE_MANAGEMENT";
    public static final String ADVANCED_NOTIFICATION_MANAGEMENT = "ADVANCED_NOTIFICATION_MANAGEMENT";
    public static final String PROFITABILITY_MANAGEMENT = "PROFITABILITY_MANAGEMENT";
    public static final String INFLATION_POLICY_MANAGEMENT = "INFLATION_POLICY_MANAGEMENT";
    public static final String RATE_RESOLUTION_MANAGEMENT = "RATE_RESOLUTION_MANAGEMENT";
    public static final String MEMBER_COST_ROLE_MANAGEMENT = "MEMBER_COST_ROLE_MANAGEMENT";
}
