package com.company.scopery.modules.aiaction.realtime.domain.enums;

public enum AiActionEventType {
    EXECUTION_QUEUED,
    EXECUTION_STARTED,
    STEP_STARTED,
    STEP_PROGRESS,
    STEP_COMPLETED,
    STEP_FAILED,
    EXECUTION_WAITING_FOR_CONFIRMATION,
    EXECUTION_PAUSING,
    EXECUTION_PAUSED,
    EXECUTION_RESUMING,
    EXECUTION_RESUMED,
    EXECUTION_CANCEL_REQUESTED,
    EXECUTION_CANCELLED,
    EXECUTION_PARTIALLY_COMPLETED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    COMPENSATION_STARTED,
    COMPENSATION_STEP_COMPLETED,
    COMPENSATION_COMPLETED,
    HEARTBEAT
}
