services:

  postgres:
    image: postgres:16-alpine
    container_name: scopery-postgres
    environment:
      POSTGRES_DB: scopery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scopery"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: scopery-redis
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  scopery-backend:
    build: .
    container_name: scopery-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://scopery-postgres:5432/scopery
      REDIS_HOST: scopery-redis
      REDIS_PORT: "6379"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
