FROM eclipse-temurin:21-jre-alpine
RUN addgroup -S scopery && adduser -S scopery -G scopery
USER scopery:scopery
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
