package com.company.scopery.modules.resourcecapacity.shared.constant;

public final class CapacityActivityActions {

    public static final String CAPACITY_CALENDAR_CREATED = "CAPACITY_CALENDAR_CREATED";
    public static final String CAPACITY_CALENDAR_UPDATED = "CAPACITY_CALENDAR_UPDATED";
    public static final String CAPACITY_CALENDAR_ACTIVATED = "CAPACITY_CALENDAR_ACTIVATED";
    public static final String CAPACITY_CALENDAR_DEACTIVATED = "CAPACITY_CALENDAR_DEACTIVATED";
    public static final String CAPACITY_CALENDAR_ARCHIVED = "CAPACITY_CALENDAR_ARCHIVED";
    public static final String CAPACITY_CALENDAR_DEFAULT_CHANGED = "CAPACITY_CALENDAR_DEFAULT_CHANGED";
    public static final String CAPACITY_DAY_RULES_UPDATED = "CAPACITY_DAY_RULES_UPDATED";
    public static final String CAPACITY_EXCEPTION_CREATED = "CAPACITY_EXCEPTION_CREATED";
    public static final String CAPACITY_EXCEPTION_UPDATED = "CAPACITY_EXCEPTION_UPDATED";
    public static final String CAPACITY_EXCEPTION_DELETED = "CAPACITY_EXCEPTION_DELETED";
    public static final String CAPACITY_PROFILE_CREATED = "CAPACITY_PROFILE_CREATED";
    public static final String CAPACITY_PROFILE_UPDATED = "CAPACITY_PROFILE_UPDATED";
    public static final String CAPACITY_PROFILE_ACTIVATED = "CAPACITY_PROFILE_ACTIVATED";
    public static final String CAPACITY_PROFILE_DEACTIVATED = "CAPACITY_PROFILE_DEACTIVATED";
    public static final String CAPACITY_PROFILE_ARCHIVED = "CAPACITY_PROFILE_ARCHIVED";
    public static final String PROJECT_ALLOCATION_CREATED = "PROJECT_ALLOCATION_CREATED";
    public static final String PROJECT_ALLOCATION_UPDATED = "PROJECT_ALLOCATION_UPDATED";
    public static final String PROJECT_ALLOCATION_ACTIVATED = "PROJECT_ALLOCATION_ACTIVATED";
    public static final String PROJECT_ALLOCATION_DEACTIVATED = "PROJECT_ALLOCATION_DEACTIVATED";
    public static final String PROJECT_ALLOCATION_ARCHIVED = "PROJECT_ALLOCATION_ARCHIVED";

    // Phase 37
    public static final String RESOURCE_PROFILE_CREATED = "RESOURCE_PROFILE_CREATED";
    public static final String RESOURCE_PROFILE_UPDATED = "RESOURCE_PROFILE_UPDATED";
    public static final String RESOURCE_PROFILE_ARCHIVED = "RESOURCE_PROFILE_ARCHIVED";
    public static final String RESOURCE_PROFILE_SYNCED = "RESOURCE_PROFILE_SYNCED_FROM_MEMBER";
    public static final String RESOURCE_ROLE_CREATED = "RESOURCE_ROLE_CREATED";
    public static final String RESOURCE_ROLE_UPDATED = "RESOURCE_ROLE_UPDATED";
    public static final String RESOURCE_ROLE_ARCHIVED = "RESOURCE_ROLE_ARCHIVED";
    public static final String RESOURCE_SKILL_CREATED = "RESOURCE_SKILL_CREATED";
    public static final String RESOURCE_SKILL_UPDATED = "RESOURCE_SKILL_UPDATED";
    public static final String RESOURCE_SKILL_ARCHIVED = "RESOURCE_SKILL_ARCHIVED";
    public static final String RESOURCE_SKILL_ASSIGNED = "RESOURCE_SKILL_ASSIGNED";
    public static final String TASK_RESOURCE_ASSIGNED = "TASK_RESOURCE_ASSIGNED";
    public static final String EFFORT_ESTIMATE_CREATED = "EFFORT_ESTIMATE_CREATED";
    public static final String EFFORT_ESTIMATE_UPDATED = "EFFORT_ESTIMATE_UPDATED";
    public static final String EFFORT_FORECAST_REBUILT = "EFFORT_FORECAST_REBUILT";
    public static final String ACTUAL_EFFORT_RECORDED = "ACTUAL_EFFORT_RECORDED";
    public static final String UTILIZATION_REBUILT = "RESOURCE_UTILIZATION_REBUILT";
    public static final String CAPACITY_SUMMARY_REBUILT = "PROJECT_CAPACITY_SUMMARY_REBUILT";
    public static final String WORKLOAD_SNAPSHOT_CREATED = "WORKLOAD_SNAPSHOT_CREATED";
    public static final String RESOURCE_RISK_FLAG_CREATED = "RESOURCE_RISK_FLAG_CREATED";
    public static final String RESOURCE_RISK_FLAG_MITIGATED = "RESOURCE_RISK_FLAG_MITIGATED";
    public static final String RESOURCE_RISK_FLAG_CLOSED = "RESOURCE_RISK_FLAG_CLOSED";
    public static final String ASSIGNMENT_CONFLICT_DETECTED = "ASSIGNMENT_CONFLICT_DETECTED";
    public static final String ASSIGNMENT_CONFLICT_ACKNOWLEDGED = "ASSIGNMENT_CONFLICT_ACKNOWLEDGED";
    public static final String RESOURCE_COST_INPUT_REBUILT = "RESOURCE_COST_INPUT_REBUILT";
    public static final String THRESHOLD_POLICY_UPDATED = "UTILIZATION_THRESHOLD_POLICY_UPDATED";

    private CapacityActivityActions() {}
}
