package com.company.scopery.modules.projectfinance.shared.constant;

public final class ProjectFinanceActivityActions {
    public static final String PROJECT_FINANCE_SCENARIO_CREATED = "PROJECT_FINANCE_SCENARIO_CREATED";
    public static final String PROJECT_FINANCE_SCENARIO_UPDATED = "PROJECT_FINANCE_SCENARIO_UPDATED";
    public static final String PROJECT_FINANCE_SCENARIO_RECALCULATED = "PROJECT_FINANCE_SCENARIO_RECALCULATED";
    public static final String PROJECT_FINANCE_SCENARIO_APPROVED = "PROJECT_FINANCE_SCENARIO_APPROVED";
    public static final String PROJECT_FINANCE_SCENARIO_MARKED_CURRENT = "PROJECT_FINANCE_SCENARIO_MARKED_CURRENT";
    public static final String PROJECT_FINANCE_SCENARIO_ARCHIVED = "PROJECT_FINANCE_SCENARIO_ARCHIVED";
    public static final String PROJECT_FINANCE_SCENARIO_DUPLICATED = "PROJECT_FINANCE_SCENARIO_DUPLICATED";
    public static final String PROJECT_CUSTOM_COST_CREATED = "PROJECT_CUSTOM_COST_CREATED";
    public static final String PROJECT_CUSTOM_COST_UPDATED = "PROJECT_CUSTOM_COST_UPDATED";
    public static final String PROJECT_CUSTOM_COST_ARCHIVED = "PROJECT_CUSTOM_COST_ARCHIVED";
    public static final String PROJECT_VENDOR_COST_CREATED = "PROJECT_VENDOR_COST_CREATED";
    public static final String PROJECT_VENDOR_COST_UPDATED = "PROJECT_VENDOR_COST_UPDATED";
    public static final String PROJECT_VENDOR_COST_ARCHIVED = "PROJECT_VENDOR_COST_ARCHIVED";
    public static final String PROJECT_REVENUE_SPLIT_UPDATED = "PROJECT_REVENUE_SPLIT_UPDATED";
    public static final String PROJECT_OVERHEAD_POLICY_UPDATED = "PROJECT_OVERHEAD_POLICY_UPDATED";
    public static final String PROJECT_CONTINGENCY_UPDATED = "PROJECT_CONTINGENCY_UPDATED";
    private ProjectFinanceActivityActions() {}
}
