package com.company.scopery.common.audit;

public enum AuditEventType {
    ORGANIZATION_CREATED,
    WORKSPACE_CREATED,
    ORG_TEAM_CREATED,
    ORG_MEMBER_ENROLLED,
    ORG_MEMBER_ACTIVATED,
    ORG_MEMBER_SUSPENDED,
    ORG_MEMBER_REMOVED,
    ACCESS_GRANT_CREATED,
    ACCESS_GRANT_DELEGATED,
    ACCESS_GRANT_REVOKED,
    IAM_AUTHORIZATION_DENIED,
    IAM_DELEGATION_REJECTED
}
