CREATE TABLE IF NOT EXISTS project_finance_scenario (
    id UUID NOT NULL,
    project_id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    estimation_run_id UUID,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    scenario_version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    currency_code VARCHAR(10) NOT NULL,
    planned_revenue NUMERIC(20,4) NOT NULL DEFAULT 0,
    revenue_split_method VARCHAR(50),
    contingency_method VARCHAR(50) NOT NULL DEFAULT 'NONE',
    contingency_percent NUMERIC(10,4),
    contingency_fixed_amount NUMERIC(20,4),
    overhead_method VARCHAR(50) NOT NULL DEFAULT 'NONE',
    overhead_percent NUMERIC(10,4),
    overhead_fixed_amount NUMERIC(20,4),
    target_margin_percent NUMERIC(10,4),
    assumptions_json TEXT,
    current_flag BOOLEAN NOT NULL DEFAULT FALSE,
    approved_at TIMESTAMPTZ,
    formula_version VARCHAR(50),
    version INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT pk_project_finance_scenario PRIMARY KEY (id),
    CONSTRAINT uq_project_finance_scenario_code UNIQUE (project_id, code)
);
CREATE INDEX IF NOT EXISTS idx_project_finance_scenario_project ON project_finance_scenario(project_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_finance_scenario_current ON project_finance_scenario(project_id) WHERE current_flag = TRUE;

CREATE TABLE IF NOT EXISTS project_finance_summary (
    id UUID NOT NULL,
    finance_scenario_id UUID NOT NULL,
    project_id UUID NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    total_estimate_hours NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_labor_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_custom_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_vendor_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_contingency NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_direct_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    total_overhead NUMERIC(20,4) NOT NULL DEFAULT 0,
    budget_of_costs NUMERIC(20,4) NOT NULL DEFAULT 0,
    planned_revenue NUMERIC(20,4) NOT NULL DEFAULT 0,
    gross_margin NUMERIC(20,4) NOT NULL DEFAULT 0,
    gross_margin_percent NUMERIC(10,4) NOT NULL DEFAULT 0,
    profit_before_tax NUMERIC(20,4) NOT NULL DEFAULT 0,
    pbt_percent NUMERIC(10,4) NOT NULL DEFAULT 0,
    average_cost_rate NUMERIC(20,4),
    formula_version VARCHAR(50),
    version INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT pk_project_finance_summary PRIMARY KEY (id),
    CONSTRAINT uq_project_finance_summary_scenario UNIQUE (finance_scenario_id)
);

CREATE TABLE IF NOT EXISTS project_finance_phase (
    id UUID NOT NULL,
    finance_scenario_id UUID NOT NULL,
    project_phase_id UUID NOT NULL,
    phase_name_snapshot VARCHAR(255) NOT NULL,
    phase_order INTEGER NOT NULL DEFAULT 0,
    estimate_hours NUMERIC(20,4) NOT NULL DEFAULT 0,
    labor_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    custom_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    vendor_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    contingency_amount NUMERIC(20,4) NOT NULL DEFAULT 0,
    direct_cost NUMERIC(20,4) NOT NULL DEFAULT 0,
    overhead_amount NUMERIC(20,4) NOT NULL DEFAULT 0,
    budget_of_costs NUMERIC(20,4) NOT NULL DEFAULT 0,
    planned_revenue NUMERIC(20,4) NOT NULL DEFAULT 0,
    revenue_percent NUMERIC(10,4) NOT NULL DEFAULT 0,
    gross_margin NUMERIC(20,4) NOT NULL DEFAULT 0,
    gross_margin_percent NUMERIC(10,4) NOT NULL DEFAULT 0,
    profit_before_tax NUMERIC(20,4) NOT NULL DEFAULT 0,
    pbt_percent NUMERIC(10,4) NOT NULL DEFAULT 0,
    version INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT pk_project_finance_phase PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_project_finance_phase_scenario ON project_finance_phase(finance_scenario_id);

CREATE TABLE IF NOT EXISTS project_finance_custom_cost (
    id UUID NOT NULL,
    finance_scenario_id UUID NOT NULL,
    project_phase_id UUID,
    category VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    amount NUMERIC(20,4) NOT NULL DEFAULT 0,
    currency_code VARCHAR(10) NOT NULL,
    cost_date TIMESTAMPTZ,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    version INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT pk_project_finance_custom_cost PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_project_finance_custom_cost_scenario ON project_finance_custom_cost(finance_scenario_id);

CREATE TABLE IF NOT EXISTS project_finance_vendor_cost (
    id UUID NOT NULL,
    finance_scenario_id UUID NOT NULL,
    project_phase_id UUID,
    vendor_name VARCHAR(255) NOT NULL,
    description TEXT,
    amount NUMERIC(20,4) NOT NULL DEFAULT 0,
    currency_code VARCHAR(10) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    version INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT pk_project_finance_vendor_cost PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_project_finance_vendor_cost_scenario ON project_finance_vendor_cost(finance_scenario_id);
