-- Phase 25: RAID / Decision management

CREATE TABLE IF NOT EXISTS project_raid_item (
    id UUID NOT NULL,
    project_id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    code VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    owner_user_id UUID,
    severity VARCHAR(50),
    probability VARCHAR(50),
    impact VARCHAR(50),
    risk_score INT,
    risk_score_formula_version VARCHAR(50),
    risk_response_strategy VARCHAR(50),
    risk_trigger TEXT,
    target_resolution_date DATE,
    assumption_statement TEXT,
    validation_status VARCHAR(50),
    validation_owner UUID,
    validation_due_date DATE,
    impact_if_false TEXT,
    issue_category VARCHAR(50),
    impact_summary TEXT,
    root_cause TEXT,
    resolution_plan TEXT,
    resolution_due_date DATE,
    resolved_at TIMESTAMPTZ,
    resolved_by UUID,
    dependency_type VARCHAR(50),
    escalation_level VARCHAR(50),
    escalation_reason TEXT,
    escalated_at TIMESTAMPTZ,
    escalated_by UUID,
    linked_change_request_id UUID,
    outcome_note TEXT,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT pk_project_raid_item PRIMARY KEY (id),
    CONSTRAINT fk_project_raid_item_project FOREIGN KEY (project_id) REFERENCES project_project(id),
    CONSTRAINT ck_project_raid_item_type CHECK (type IN ('RISK','ASSUMPTION','ISSUE','DEPENDENCY','ACTION'))
);
CREATE INDEX IF NOT EXISTS idx_project_raid_item_project ON project_raid_item(project_id);
CREATE INDEX IF NOT EXISTS idx_project_raid_item_type ON project_raid_item(project_id, type);

CREATE TABLE IF NOT EXISTS project_raid_action (
    id UUID NOT NULL,
    raid_item_id UUID NOT NULL,
    project_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    owner_user_id UUID,
    due_date DATE,
    status VARCHAR(50) NOT NULL,
    linked_task_id UUID,
    completion_note TEXT,
    completed_at TIMESTAMPTZ,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT pk_project_raid_action PRIMARY KEY (id),
    CONSTRAINT fk_project_raid_action_item FOREIGN KEY (raid_item_id) REFERENCES project_raid_item(id),
    CONSTRAINT ck_project_raid_action_status CHECK (status IN ('OPEN','IN_PROGRESS','DONE','CANCELLED','OVERDUE'))
);

CREATE TABLE IF NOT EXISTS project_raid_link (
    id UUID NOT NULL,
    raid_item_id UUID NOT NULL,
    project_id UUID NOT NULL,
    link_type VARCHAR(100) NOT NULL,
    target_type VARCHAR(100) NOT NULL,
    target_id UUID NOT NULL,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    CONSTRAINT pk_project_raid_link PRIMARY KEY (id),
    CONSTRAINT fk_project_raid_link_item FOREIGN KEY (raid_item_id) REFERENCES project_raid_item(id)
);

CREATE TABLE IF NOT EXISTS project_decision_record (
    id UUID NOT NULL,
    project_id UUID NOT NULL,
    workspace_id UUID NOT NULL,
    code VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    rationale TEXT,
    outcome TEXT,
    decided_at TIMESTAMPTZ,
    decided_by UUID,
    superseded_by_decision_id UUID,
    linked_change_request_id UUID,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT pk_project_decision_record PRIMARY KEY (id),
    CONSTRAINT fk_project_decision_record_project FOREIGN KEY (project_id) REFERENCES project_project(id),
    CONSTRAINT ck_project_decision_record_status CHECK (status IN ('PROPOSED','UNDER_REVIEW','DECIDED','REJECTED','SUPERSEDED','ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS project_decision_option (
    id UUID NOT NULL,
    decision_id UUID NOT NULL,
    project_id UUID NOT NULL,
    option_title VARCHAR(255) NOT NULL,
    option_description TEXT,
    pros TEXT,
    cons TEXT,
    estimated_impact TEXT,
    selected_flag BOOLEAN NOT NULL DEFAULT FALSE,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    CONSTRAINT pk_project_decision_option PRIMARY KEY (id),
    CONSTRAINT fk_project_decision_option_decision FOREIGN KEY (decision_id) REFERENCES project_decision_record(id)
);

CREATE TABLE IF NOT EXISTS project_decision_impact (
    id UUID NOT NULL,
    decision_id UUID NOT NULL,
    project_id UUID NOT NULL,
    scope_impact TEXT,
    schedule_impact_days INT,
    estimate_hours_impact NUMERIC(12,2),
    cost_impact NUMERIC(18,2),
    revenue_impact NUMERIC(18,2),
    margin_impact NUMERIC(18,2),
    risk_impact TEXT,
    deliverable_impact TEXT,
    acceptance_impact TEXT,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    CONSTRAINT pk_project_decision_impact PRIMARY KEY (id),
    CONSTRAINT fk_project_decision_impact_decision FOREIGN KEY (decision_id) REFERENCES project_decision_record(id)
);
