-- Phase 26 fix: rename project_* quality tables to quality_* module prefix (CLAUDE.md §12)
-- Pattern: same as V62 (scope) / V69 (raid).

ALTER TABLE IF EXISTS project_quality_plan RENAME TO quality_plan;
ALTER TABLE IF EXISTS project_test_plan RENAME TO quality_test_plan;
ALTER TABLE IF EXISTS project_test_suite RENAME TO quality_test_suite;
ALTER TABLE IF EXISTS project_test_case RENAME TO quality_test_case;
ALTER TABLE IF EXISTS project_test_step RENAME TO quality_test_step;
ALTER TABLE IF EXISTS project_test_case_coverage RENAME TO quality_test_case_coverage;
ALTER TABLE IF EXISTS project_test_run RENAME TO quality_test_run;
ALTER TABLE IF EXISTS project_test_case_result RENAME TO quality_test_case_result;
ALTER TABLE IF EXISTS project_test_step_result RENAME TO quality_test_step_result;
ALTER TABLE IF EXISTS project_defect RENAME TO quality_defect;
ALTER TABLE IF EXISTS project_defect_link RENAME TO quality_defect_link;
ALTER TABLE IF EXISTS project_release_package RENAME TO quality_release_package;
ALTER TABLE IF EXISTS project_release_item RENAME TO quality_release_item;
ALTER TABLE IF EXISTS project_release_readiness_check RENAME TO quality_release_readiness_check;
ALTER TABLE IF EXISTS project_deployment_environment RENAME TO quality_deployment_environment;
ALTER TABLE IF EXISTS project_rollback_plan RENAME TO quality_rollback_plan;
ALTER TABLE IF EXISTS project_deployment_record RENAME TO quality_deployment_record;

-- Primary keys
ALTER TABLE quality_plan RENAME CONSTRAINT pk_project_quality_plan TO pk_quality_plan;
ALTER TABLE quality_test_plan RENAME CONSTRAINT pk_project_test_plan TO pk_quality_test_plan;
ALTER TABLE quality_test_suite RENAME CONSTRAINT pk_project_test_suite TO pk_quality_test_suite;
ALTER TABLE quality_test_case RENAME CONSTRAINT pk_project_test_case TO pk_quality_test_case;
ALTER TABLE quality_test_step RENAME CONSTRAINT pk_project_test_step TO pk_quality_test_step;
ALTER TABLE quality_test_case_coverage RENAME CONSTRAINT pk_project_test_case_coverage TO pk_quality_test_case_coverage;
ALTER TABLE quality_test_run RENAME CONSTRAINT pk_project_test_run TO pk_quality_test_run;
ALTER TABLE quality_test_case_result RENAME CONSTRAINT pk_project_test_case_result TO pk_quality_test_case_result;
ALTER TABLE quality_test_step_result RENAME CONSTRAINT pk_project_test_step_result TO pk_quality_test_step_result;
ALTER TABLE quality_defect RENAME CONSTRAINT pk_project_defect TO pk_quality_defect;
ALTER TABLE quality_defect_link RENAME CONSTRAINT pk_project_defect_link TO pk_quality_defect_link;
ALTER TABLE quality_release_package RENAME CONSTRAINT pk_project_release_package TO pk_quality_release_package;
ALTER TABLE quality_release_item RENAME CONSTRAINT pk_project_release_item TO pk_quality_release_item;
ALTER TABLE quality_release_readiness_check RENAME CONSTRAINT pk_project_release_readiness_check TO pk_quality_release_readiness_check;
ALTER TABLE quality_deployment_environment RENAME CONSTRAINT pk_project_deployment_environment TO pk_quality_deployment_environment;
ALTER TABLE quality_rollback_plan RENAME CONSTRAINT pk_project_rollback_plan TO pk_quality_rollback_plan;
ALTER TABLE quality_deployment_record RENAME CONSTRAINT pk_project_deployment_record TO pk_quality_deployment_record;

-- Foreign keys
ALTER TABLE quality_plan RENAME CONSTRAINT fk_project_quality_plan_project TO fk_quality_plan_project_project;
ALTER TABLE quality_test_plan RENAME CONSTRAINT fk_project_test_plan_project TO fk_quality_test_plan_project_project;
ALTER TABLE quality_test_suite RENAME CONSTRAINT fk_project_test_suite_plan TO fk_quality_test_suite_quality_test_plan;
ALTER TABLE quality_test_case RENAME CONSTRAINT fk_project_test_case_project TO fk_quality_test_case_project_project;
ALTER TABLE quality_test_step RENAME CONSTRAINT fk_project_test_step_case TO fk_quality_test_step_quality_test_case;
ALTER TABLE quality_test_case_coverage RENAME CONSTRAINT fk_project_test_case_coverage_case TO fk_quality_test_case_coverage_quality_test_case;
ALTER TABLE quality_test_run RENAME CONSTRAINT fk_project_test_run_project TO fk_quality_test_run_project_project;
ALTER TABLE quality_test_case_result RENAME CONSTRAINT fk_project_test_case_result_run TO fk_quality_test_case_result_quality_test_run;
ALTER TABLE quality_test_step_result RENAME CONSTRAINT fk_project_test_step_result_case TO fk_quality_test_step_result_quality_test_case_result;
ALTER TABLE quality_defect RENAME CONSTRAINT fk_project_defect_project TO fk_quality_defect_project_project;
ALTER TABLE quality_defect_link RENAME CONSTRAINT fk_project_defect_link_defect TO fk_quality_defect_link_quality_defect;
ALTER TABLE quality_release_package RENAME CONSTRAINT fk_project_release_package_project TO fk_quality_release_package_project_project;
ALTER TABLE quality_release_item RENAME CONSTRAINT fk_project_release_item_package TO fk_quality_release_item_quality_release_package;
ALTER TABLE quality_release_readiness_check RENAME CONSTRAINT fk_project_release_readiness_check_package TO fk_quality_release_readiness_check_quality_release_package;
ALTER TABLE quality_rollback_plan RENAME CONSTRAINT fk_project_rollback_plan_project TO fk_quality_rollback_plan_project_project;
ALTER TABLE quality_deployment_record RENAME CONSTRAINT fk_project_deployment_record_project TO fk_quality_deployment_record_project_project;
ALTER TABLE quality_deployment_record RENAME CONSTRAINT fk_project_deployment_record_release TO fk_quality_deployment_record_quality_release_package;
ALTER TABLE quality_deployment_record RENAME CONSTRAINT fk_project_deployment_record_env TO fk_quality_deployment_record_quality_deployment_environment;

-- Unique / check constraints
ALTER TABLE quality_plan RENAME CONSTRAINT ck_project_quality_plan_status TO ck_quality_plan_status;
ALTER TABLE quality_test_plan RENAME CONSTRAINT ck_project_test_plan_status TO ck_quality_test_plan_status;
ALTER TABLE quality_test_plan RENAME CONSTRAINT ck_project_test_plan_level TO ck_quality_test_plan_level;
ALTER TABLE quality_test_suite RENAME CONSTRAINT ck_project_test_suite_status TO ck_quality_test_suite_status;
ALTER TABLE quality_test_case RENAME CONSTRAINT ck_project_test_case_status TO ck_quality_test_case_status;
ALTER TABLE quality_test_case RENAME CONSTRAINT ck_project_test_case_type TO ck_quality_test_case_type;
ALTER TABLE quality_test_case RENAME CONSTRAINT ck_project_test_case_priority TO ck_quality_test_case_priority;
ALTER TABLE quality_test_case_coverage RENAME CONSTRAINT ck_project_test_case_coverage_type TO ck_quality_test_case_coverage_type;
ALTER TABLE quality_test_run RENAME CONSTRAINT ck_project_test_run_status TO ck_quality_test_run_status;
ALTER TABLE quality_test_run RENAME CONSTRAINT ck_project_test_run_type TO ck_quality_test_run_type;
ALTER TABLE quality_test_case_result RENAME CONSTRAINT ck_project_test_case_result_status TO ck_quality_test_case_result_status;
ALTER TABLE quality_test_step_result RENAME CONSTRAINT ck_project_test_step_result_status TO ck_quality_test_step_result_status;
ALTER TABLE quality_defect RENAME CONSTRAINT ck_project_defect_status TO ck_quality_defect_status;
ALTER TABLE quality_defect RENAME CONSTRAINT ck_project_defect_severity TO ck_quality_defect_severity;
ALTER TABLE quality_defect RENAME CONSTRAINT ck_project_defect_priority TO ck_quality_defect_priority;
ALTER TABLE quality_defect RENAME CONSTRAINT ck_project_defect_category TO ck_quality_defect_category;
ALTER TABLE quality_defect_link RENAME CONSTRAINT ck_project_defect_link_type TO ck_quality_defect_link_type;
ALTER TABLE quality_release_package RENAME CONSTRAINT uq_project_release_package_code TO uq_quality_release_package_code;
ALTER TABLE quality_release_package RENAME CONSTRAINT uq_project_release_package_version TO uq_quality_release_package_version;
ALTER TABLE quality_release_package RENAME CONSTRAINT ck_project_release_package_status TO ck_quality_release_package_status;
ALTER TABLE quality_release_package RENAME CONSTRAINT ck_project_release_package_type TO ck_quality_release_package_type;
ALTER TABLE quality_release_item RENAME CONSTRAINT ck_project_release_item_status TO ck_quality_release_item_status;
ALTER TABLE quality_release_readiness_check RENAME CONSTRAINT ck_project_release_readiness_check_status TO ck_quality_release_readiness_check_status;
ALTER TABLE quality_deployment_environment RENAME CONSTRAINT ck_project_deployment_environment_type TO ck_quality_deployment_environment_type;
ALTER TABLE quality_rollback_plan RENAME CONSTRAINT ck_project_rollback_plan_status TO ck_quality_rollback_plan_status;
ALTER TABLE quality_deployment_record RENAME CONSTRAINT ck_project_deployment_record_status TO ck_quality_deployment_record_status;

-- Indexes
ALTER INDEX IF EXISTS idx_project_quality_plan_project RENAME TO idx_quality_plan_project;
ALTER INDEX IF EXISTS idx_project_test_plan_project RENAME TO idx_quality_test_plan_project;
ALTER INDEX IF EXISTS uq_project_test_case_code RENAME TO uq_quality_test_case_code;
ALTER INDEX IF EXISTS idx_project_test_case_project RENAME TO idx_quality_test_case_project;
ALTER INDEX IF EXISTS uq_project_test_step_order RENAME TO uq_quality_test_step_order;
ALTER INDEX IF EXISTS idx_project_test_run_project RENAME TO idx_quality_test_run_project;
ALTER INDEX IF EXISTS idx_project_defect_project RENAME TO idx_quality_defect_project;
ALTER INDEX IF EXISTS idx_project_defect_status RENAME TO idx_quality_defect_status;
ALTER INDEX IF EXISTS idx_project_release_package_project RENAME TO idx_quality_release_package_project;
ALTER INDEX IF EXISTS uq_project_deployment_environment_code RENAME TO uq_quality_deployment_environment_code;
ALTER INDEX IF EXISTS idx_project_deployment_record_project RENAME TO idx_quality_deployment_record_project;
