package com.company.scopery.modules.collaboration.meeting.domain.enums;
public enum MeetingType {
    PROJECT_STATUS, CLIENT_STATUS, SPRINT_PLANNING, SPRINT_REVIEW, RETROSPECTIVE, REQUIREMENT_REVIEW, DESIGN_REVIEW, TECHNICAL_REVIEW, RAID_REVIEW, CHANGE_CONTROL, QUALITY_REVIEW, RELEASE_READINESS, UAT_REVIEW, DELIVERABLE_ACCEPTANCE, DECISION_MEETING, GENERAL, OTHER
}
