package com.company.scopery.modules.traceability.shared.constant;
public final class TraceabilityEntityTypes {
    public static final String APPLICATION = "APPLICATION";
    public static final String APP_MODULE = "APP_MODULE";
    public static final String APP_COMPONENT = "APP_COMPONENT";
    public static final String SCREEN = "SCREEN";
    public static final String SCREEN_SECTION = "SCREEN_SECTION";
    public static final String SCREEN_FIELD = "SCREEN_FIELD";
    public static final String SCREEN_ACTION = "SCREEN_ACTION";
    public static final String API_ENDPOINT = "API_ENDPOINT";
    public static final String DATA_ENTITY = "DATA_ENTITY";
    public static final String REQUIREMENT = "REQUIREMENT";
    public static final String REQUIREMENT_VERSION = "REQUIREMENT_VERSION";
    public static final String REQUIREMENT_SOURCE = "REQUIREMENT_SOURCE";
    public static final String REQUIREMENT_CRITERIA = "REQUIREMENT_CRITERIA";
    public static final String TRACE_LINK = "TRACE_LINK";
    public static final String FUNCTIONAL_ITEM = "FUNCTIONAL_ITEM";
    public static final String NON_FUNCTIONAL_ITEM = "NON_FUNCTIONAL_ITEM";
    public static final String BUSINESS_RULE = "BUSINESS_RULE";
    public static final String FUNCTIONAL_ITEM_CUSTOM_PROP = "FUNCTIONAL_ITEM_CUSTOM_PROP";
    public static final String FUNCTIONAL_ITEM_ANCHOR = "FUNCTIONAL_ITEM_ANCHOR";
    public static final String STRUCTURE_RELATION = "STRUCTURE_RELATION";
    public static final String FUNCTION_SCREEN = "FUNCTION_SCREEN";
    public static final String FUNCTION_API = "FUNCTION_API";
    public static final String COMMUNICATION_SPECIFICATION = "COMMUNICATION_SPECIFICATION";
    public static final String FUNCTION_COMMUNICATION = "FUNCTION_COMMUNICATION";
    public static final String SCREEN_COMPONENT = "SCREEN_COMPONENT";
    public static final String NFR_SCOPE_TARGET   = "NFR_SCOPE_TARGET";
    public static final String FUNCTION_WORKFLOW      = "FUNCTION_WORKFLOW";
    public static final String FUNCTION_WORKFLOW_STEP = "FUNCTION_WORKFLOW_STEP";
    public static final String USE_CASE                      = "USE_CASE";
    public static final String USE_CASE_FLOW                 = "USE_CASE_FLOW";
    public static final String USE_CASE_FLOW_STEP            = "USE_CASE_FLOW_STEP";
    public static final String USE_CASE_CONDITION            = "USE_CASE_CONDITION";
    public static final String USE_CASE_BUSINESS_RULE        = "USE_CASE_BUSINESS_RULE";
    public static final String USE_CASE_ACCEPTANCE_CRITERION = "USE_CASE_ACCEPTANCE_CRITERION";
    // Screen Design Spec
    public static final String SCREEN_MODE              = "SCREEN_MODE";
    public static final String DATA_ENTITY_FIELD        = "DATA_ENTITY_FIELD";
    public static final String VALIDATION_RULE_TYPE     = "VALIDATION_RULE_TYPE";
    public static final String COMPONENT_OPTION         = "COMPONENT_OPTION";
    public static final String SCREEN_FIELD_MODE_CONFIG = "SCREEN_FIELD_MODE_CONFIG";
    public static final String SCREEN_FIELD_VALIDATION  = "SCREEN_FIELD_VALIDATION";
    public static final String SCREEN_SPEC_DOCUMENT     = "SCREEN_SPEC_DOCUMENT";
    public static final String SPEC_DOC_REVISION        = "SPEC_DOC_REVISION";
    public static final String SCREEN_PROCESS_ITEM      = "SCREEN_PROCESS_ITEM";
    public static final String SCREEN_EVENT_ITEM        = "SCREEN_EVENT_ITEM";
    public static final String COMPONENT_FIELD          = "COMPONENT_FIELD";
    private TraceabilityEntityTypes() {}
}
