package com.company.scopery.modules.traceability.shared.constant;
public final class TraceabilityTableNames {
    public static final String APPLICATION = "app_registry_application";
    public static final String PROJECT_MAPPING = "app_registry_project_mapping";
    public static final String APP_MODULE = "app_registry_module";
    public static final String APP_COMPONENT = "app_registry_component";
    public static final String SCREEN = "app_registry_screen";
    public static final String SCREEN_SECTION = "app_registry_screen_section";
    public static final String SCREEN_FIELD = "app_registry_screen_field";
    public static final String SCREEN_ACTION = "app_registry_screen_action";
    public static final String API_ENDPOINT = "app_registry_api_endpoint";
    public static final String DATA_ENTITY = "app_registry_data_entity";
    public static final String REQUIREMENT = "requirements_requirement";
    public static final String REQUIREMENT_VERSION = "requirements_requirement_version";
    public static final String REQUIREMENT_SOURCE = "requirements_requirement_source";
    public static final String REQUIREMENT_CRITERIA = "requirements_acceptance_criteria";
    public static final String TRACE_LINK = "traceability_link";
    public static final String FUNCTIONAL_ITEM = "app_functional_item";
    public static final String FUNCTIONAL_ITEM_CUSTOM_PROPERTY = "app_functional_item_custom_property";
    public static final String FUNCTIONAL_ITEM_ANCHOR = "app_functional_item_anchor";
    public static final String NON_FUNCTIONAL_ITEM = "app_non_functional_item";
    public static final String BUSINESS_RULE = "app_business_rule";
    public static final String STRUCTURE_RELATION = "app_structure_relation";
    public static final String FUNCTION_SCREEN = "app_function_screen";
    public static final String FUNCTION_API = "app_function_api";
    public static final String SCREEN_COMPONENT = "app_screen_component";
    public static final String NFR_SCOPE_TARGET = "app_nfr_scope_target";
    public static final String COMMUNICATION_SPECIFICATION = "app_communication_specification";
    public static final String FUNCTION_COMMUNICATION = "app_function_communication";
    public static final String USE_CASE                      = "app_use_case";
    public static final String USE_CASE_SUPPORTING_FUNCTION  = "app_use_case_supporting_function";
    public static final String USE_CASE_CONDITION            = "app_use_case_condition";
    public static final String USE_CASE_FLOW                 = "app_use_case_flow";
    public static final String USE_CASE_FLOW_STEP            = "app_use_case_flow_step";
    public static final String USE_CASE_BUSINESS_RULE        = "app_use_case_business_rule";
    public static final String USE_CASE_ACCEPTANCE_CRITERION = "app_use_case_acceptance_criterion";
    public static final String REQUIREMENT_FUNCTION          = "app_requirement_function";
    public static final String REQUIREMENT_USE_CASE          = "app_requirement_use_case";
    // Screen Design Spec
    public static final String SCREEN_MODE                   = "app_registry_screen_mode";
    public static final String DATA_ENTITY_FIELD             = "app_registry_data_entity_field";
    public static final String VALIDATION_RULE_TYPE          = "app_registry_validation_rule_type";
    public static final String COMPONENT_OPTION              = "app_registry_component_option";
    public static final String SCREEN_FIELD_MODE_CONFIG      = "app_registry_screen_field_mode_config";
    public static final String SCREEN_FIELD_VALIDATION       = "app_registry_screen_field_validation";
    public static final String SCREEN_SPEC_DOCUMENT          = "app_registry_screen_spec_document";
    public static final String SPEC_DOC_SCREEN               = "app_registry_spec_doc_screen";
    public static final String SPEC_DOC_REVISION             = "app_registry_spec_doc_revision";
    public static final String SCREEN_PROCESS_ITEM           = "app_registry_screen_process_item";
    public static final String SCREEN_EVENT_ITEM             = "app_registry_screen_event_item";
    public static final String COMPONENT_FIELD               = "app_registry_component_field";
    private TraceabilityTableNames() {}
}
